use std::{error::Error, fmt};

use crate::core::clipboard::ClipboardInput;

const POLL_INTERVAL_MS: u64 = 250;
const PRIVACY_MARKERS: [&str; 6] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
];

#[cfg(target_os = "macos")]
use std::{
    sync::mpsc::{self, Receiver, RecvTimeoutError, Sender},
    thread::{self, JoinHandle},
    time::Duration,
};

#[cfg(target_os = "macos")]
use objc2::{msg_send, rc::autoreleasepool, runtime::NSObjectProtocol, sel};
#[cfg(target_os = "macos")]
use objc2_app_kit::{
    NSPasteboard, NSPasteboardItem, NSPasteboardType, NSPasteboardTypeFileURL,
    NSPasteboardTypeHTML, NSPasteboardTypePNG, NSPasteboardTypeString, NSPasteboardTypeTIFF,
    NSWorkspace,
};

#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) enum MacClipboardError {
    WatcherStart(&'static str),
    WatcherShutdown(&'static str),
    PasteboardAccessDenied,
    InvalidFileUrl,
    InvalidImage,
}

impl fmt::Display for MacClipboardError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::WatcherStart(operation) => {
                write!(
                    formatter,
                    "macOS clipboard watcher failed to start: {operation}"
                )
            }
            Self::WatcherShutdown(operation) => {
                write!(
                    formatter,
                    "macOS clipboard watcher failed to stop: {operation}"
                )
            }
            Self::PasteboardAccessDenied => {
                formatter.write_str("macOS denied programmatic pasteboard access")
            }
            Self::InvalidFileUrl => formatter.write_str("clipboard file URL is invalid"),
            Self::InvalidImage => formatter.write_str("clipboard image is invalid"),
        }
    }
}

impl Error for MacClipboardError {}

#[cfg(target_os = "macos")]
type MacClipboardEvent = Result<Option<ClipboardInput>, MacClipboardError>;

#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
enum PasteboardAccessBehavior {
    #[default]
    UnsupportedLegacy,
    Default,
    Ask,
    AlwaysAllow,
    AlwaysDeny,
    Unknown(isize),
}

impl PasteboardAccessBehavior {
    const fn allows_content_read(self) -> bool {
        !matches!(self, Self::AlwaysDeny)
    }
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
struct MacClipboardPrivacyFlags {
    sensitive_or_transient: bool,
}

impl MacClipboardPrivacyFlags {
    fn from_types(types: &[String]) -> Self {
        Self {
            sensitive_or_transient: types
                .iter()
                .any(|clipboard_type| is_privacy_marker(clipboard_type)),
        }
    }

    const fn should_skip(self) -> bool {
        self.sensitive_or_transient
    }
}

#[derive(Clone, Debug, Default)]
struct MacClipboardSnapshot {
    change_count: isize,
    types: Vec<String>,
    text: Option<String>,
    html: Option<String>,
    png: Option<Vec<u8>>,
    tiff: Option<Vec<u8>>,
    file_urls: Option<Vec<String>>,
    source_application: Option<String>,
    privacy_flags: MacClipboardPrivacyFlags,
    access_behavior: PasteboardAccessBehavior,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ChangeCountTracker {
    last_change_count: isize,
}

impl ChangeCountTracker {
    const fn new(initial_change_count: isize) -> Self {
        Self {
            last_change_count: initial_change_count,
        }
    }

    fn should_process(&mut self, current_change_count: isize) -> bool {
        if current_change_count == self.last_change_count {
            return false;
        }
        self.last_change_count = current_change_count;
        true
    }
}

fn is_privacy_marker(clipboard_type: &str) -> bool {
    PRIVACY_MARKERS.contains(&clipboard_type)
}

fn read_if_allowed<T>(
    behavior: PasteboardAccessBehavior,
    read: impl FnOnce() -> Result<T, MacClipboardError>,
) -> Result<T, MacClipboardError> {
    if !behavior.allows_content_read() {
        return Err(MacClipboardError::PasteboardAccessDenied);
    }
    read()
}

fn select_clipboard_input(
    snapshot: MacClipboardSnapshot,
) -> Result<Option<ClipboardInput>, MacClipboardError> {
    let _ = (
        snapshot.change_count,
        snapshot.types.len(),
        snapshot.access_behavior,
    );
    if snapshot.privacy_flags.should_skip() {
        return Ok(None);
    }

    let source_application = snapshot.source_application;
    let mut first_error = None;

    if let Some(file_urls) = snapshot.file_urls {
        match decode_file_urls(file_urls) {
            Ok(files) => {
                return Ok(Some(ClipboardInput::Files {
                    files,
                    source_app: source_application,
                }));
            }
            Err(error) => remember_first_error(&mut first_error, error),
        }
    }

    if let Some(png) = snapshot.png {
        match decode_image(&png, image::ImageFormat::Png) {
            Ok(image) => return Ok(Some(image.into_input(source_application))),
            Err(error) => remember_first_error(&mut first_error, error),
        }
    }

    if let Some(html) = snapshot.html {
        return Ok(Some(ClipboardInput::Html {
            html,
            text: snapshot.text,
            source_app: source_application,
        }));
    }

    if let Some(tiff) = snapshot.tiff {
        match decode_image(&tiff, image::ImageFormat::Tiff) {
            Ok(image) => return Ok(Some(image.into_input(source_application))),
            Err(error) => remember_first_error(&mut first_error, error),
        }
    }

    if let Some(text) = snapshot.text {
        return Ok(Some(ClipboardInput::Text {
            text,
            source_app: source_application,
        }));
    }

    match first_error {
        Some(error) => Err(error),
        None => Ok(None),
    }
}

fn remember_first_error(first_error: &mut Option<MacClipboardError>, error: MacClipboardError) {
    if first_error.is_none() {
        *first_error = Some(error);
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct CanonicalImage {
    width: u32,
    height: u32,
    rgba8: Vec<u8>,
}

impl CanonicalImage {
    fn into_input(self, source_application: Option<String>) -> ClipboardInput {
        ClipboardInput::Image {
            width: self.width,
            height: self.height,
            rgba8: self.rgba8,
            source_app: source_application,
        }
    }
}

fn decode_image(
    bytes: &[u8],
    format: image::ImageFormat,
) -> Result<CanonicalImage, MacClipboardError> {
    let image = image::load_from_memory_with_format(bytes, format)
        .map_err(|_| MacClipboardError::InvalidImage)?
        .into_rgba8();
    let (width, height) = image.dimensions();
    validate_canonical_image(width, height, image.into_raw())
}

fn validate_canonical_image(
    width: u32,
    height: u32,
    rgba8: Vec<u8>,
) -> Result<CanonicalImage, MacClipboardError> {
    let expected = u64::from(width)
        .checked_mul(u64::from(height))
        .and_then(|pixels| pixels.checked_mul(4))
        .and_then(|bytes| usize::try_from(bytes).ok())
        .ok_or(MacClipboardError::InvalidImage)?;
    if width == 0 || height == 0 || rgba8.len() != expected {
        return Err(MacClipboardError::InvalidImage);
    }
    Ok(CanonicalImage {
        width,
        height,
        rgba8,
    })
}

fn decode_file_urls(file_urls: Vec<String>) -> Result<Vec<String>, MacClipboardError> {
    file_urls
        .into_iter()
        .map(|file_url| decode_file_url(&file_url))
        .collect()
}

fn decode_file_url(file_url: &str) -> Result<String, MacClipboardError> {
    let remainder = file_url
        .strip_prefix("file://")
        .ok_or(MacClipboardError::InvalidFileUrl)?;
    let path_and_suffix = if remainder.starts_with('/') {
        remainder
    } else {
        let (authority, _path) = remainder
            .split_once('/')
            .ok_or(MacClipboardError::InvalidFileUrl)?;
        if !authority.eq_ignore_ascii_case("localhost") {
            return Err(MacClipboardError::InvalidFileUrl);
        }
        &remainder[authority.len()..]
    };
    let path = path_and_suffix
        .split(['?', '#'])
        .next()
        .ok_or(MacClipboardError::InvalidFileUrl)?;
    if !path.starts_with('/') {
        return Err(MacClipboardError::InvalidFileUrl);
    }
    percent_decode_utf8(path)
}

fn percent_decode_utf8(value: &str) -> Result<String, MacClipboardError> {
    let bytes = value.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' {
            let high = bytes
                .get(index + 1)
                .and_then(|value| hex_value(*value))
                .ok_or(MacClipboardError::InvalidFileUrl)?;
            let low = bytes
                .get(index + 2)
                .and_then(|value| hex_value(*value))
                .ok_or(MacClipboardError::InvalidFileUrl)?;
            decoded.push((high << 4) | low);
            index += 3;
        } else {
            decoded.push(bytes[index]);
            index += 1;
        }
    }
    if decoded.contains(&0) {
        return Err(MacClipboardError::InvalidFileUrl);
    }
    String::from_utf8(decoded).map_err(|_| MacClipboardError::InvalidFileUrl)
}

const fn hex_value(value: u8) -> Option<u8> {
    match value {
        b'0'..=b'9' => Some(value - b'0'),
        b'a'..=b'f' => Some(value - b'a' + 10),
        b'A'..=b'F' => Some(value - b'A' + 10),
        _ => None,
    }
}

#[cfg(target_os = "macos")]
pub(crate) struct MacClipboardWatcher {
    stop_sender: Sender<()>,
    events: Receiver<MacClipboardEvent>,
    thread: Option<JoinHandle<Result<(), MacClipboardError>>>,
}

#[cfg(target_os = "macos")]
impl MacClipboardWatcher {
    pub(crate) fn start() -> Result<Self, MacClipboardError> {
        let (ready_sender, ready_receiver) = mpsc::channel();
        let (event_sender, events) = mpsc::channel();
        let (stop_sender, stop_receiver) = mpsc::channel();
        let thread = thread::Builder::new()
            .name("litesnap-macos-clipboard-watcher".into())
            .spawn(move || watcher_thread(ready_sender, event_sender, stop_receiver))
            .map_err(|_| MacClipboardError::WatcherStart("spawn watcher thread"))?;

        match ready_receiver.recv() {
            Ok(Ok(())) => Ok(Self {
                stop_sender,
                events,
                thread: Some(thread),
            }),
            Ok(Err(error)) => {
                let _ = thread.join();
                Err(error)
            }
            Err(_) => match thread.join() {
                Ok(Err(error)) => Err(error),
                _ => Err(MacClipboardError::WatcherStart("startup handshake")),
            },
        }
    }

    pub(crate) fn events(&self) -> &Receiver<MacClipboardEvent> {
        &self.events
    }

    pub(crate) fn stop(mut self) -> Result<(), MacClipboardError> {
        self.shutdown()
    }

    fn shutdown(&mut self) -> Result<(), MacClipboardError> {
        let Some(thread) = self.thread.take() else {
            return Ok(());
        };
        let _ = self.stop_sender.send(());
        match thread.join() {
            Ok(result) => result,
            Err(_) => Err(MacClipboardError::WatcherShutdown("join watcher thread")),
        }
    }
}

#[cfg(target_os = "macos")]
impl Drop for MacClipboardWatcher {
    fn drop(&mut self) {
        let _ = self.shutdown();
    }
}

#[cfg(target_os = "macos")]
fn watcher_thread(
    ready_sender: Sender<Result<(), MacClipboardError>>,
    event_sender: Sender<MacClipboardEvent>,
    stop_receiver: Receiver<()>,
) -> Result<(), MacClipboardError> {
    let initial_change_count = autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount());
    ready_sender
        .send(Ok(()))
        .map_err(|_| MacClipboardError::WatcherStart("startup receiver disconnected"))?;

    let mut tracker = ChangeCountTracker::new(initial_change_count);
    let mut access_denied_reported = false;
    loop {
        match stop_receiver.recv_timeout(Duration::from_millis(POLL_INTERVAL_MS)) {
            Ok(()) | Err(RecvTimeoutError::Disconnected) => break,
            Err(RecvTimeoutError::Timeout) => {}
        }

        let Some(result) = autoreleasepool(|_| poll_pasteboard(&mut tracker)) else {
            continue;
        };
        match result {
            Err(MacClipboardError::PasteboardAccessDenied) => {
                if !access_denied_reported {
                    let _ = event_sender.send(Err(MacClipboardError::PasteboardAccessDenied));
                    access_denied_reported = true;
                }
            }
            Err(error) => {
                access_denied_reported = false;
                let _ = event_sender.send(Err(error));
            }
            Ok(snapshot) => {
                access_denied_reported = false;
                let _ = event_sender.send(select_clipboard_input(snapshot));
            }
        }
    }
    Ok(())
}

#[cfg(target_os = "macos")]
fn poll_pasteboard(
    tracker: &mut ChangeCountTracker,
) -> Option<Result<MacClipboardSnapshot, MacClipboardError>> {
    let pasteboard = NSPasteboard::generalPasteboard();
    let change_count = pasteboard.changeCount();
    if !tracker.should_process(change_count) {
        return None;
    }

    let source_application = frontmost_application_name();
    let access_behavior = pasteboard_access_behavior(&pasteboard);
    Some(read_if_allowed(access_behavior, || {
        capture_snapshot(
            &pasteboard,
            change_count,
            source_application,
            access_behavior,
        )
    }))
}

#[cfg(target_os = "macos")]
fn pasteboard_access_behavior(pasteboard: &NSPasteboard) -> PasteboardAccessBehavior {
    if !pasteboard.respondsToSelector(sel!(accessBehavior)) {
        return PasteboardAccessBehavior::UnsupportedLegacy;
    }

    let raw: isize = unsafe { msg_send![pasteboard, accessBehavior] };
    match raw {
        0 => PasteboardAccessBehavior::Default,
        1 => PasteboardAccessBehavior::Ask,
        2 => PasteboardAccessBehavior::AlwaysAllow,
        3 => PasteboardAccessBehavior::AlwaysDeny,
        value => PasteboardAccessBehavior::Unknown(value),
    }
}

#[cfg(target_os = "macos")]
fn frontmost_application_name() -> Option<String> {
    let application = NSWorkspace::sharedWorkspace().frontmostApplication()?;
    application
        .localizedName()
        .or_else(|| application.bundleIdentifier())
        .map(|value| value.to_string())
        .filter(|value| !value.is_empty())
}

#[cfg(target_os = "macos")]
fn capture_snapshot(
    pasteboard: &NSPasteboard,
    change_count: isize,
    source_application: Option<String>,
    access_behavior: PasteboardAccessBehavior,
) -> Result<MacClipboardSnapshot, MacClipboardError> {
    let types = pasteboard
        .types()
        .map(|types| {
            types
                .to_vec()
                .into_iter()
                .map(|clipboard_type| clipboard_type.to_string())
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    let privacy_flags = MacClipboardPrivacyFlags::from_types(&types);
    let mut snapshot = MacClipboardSnapshot {
        change_count,
        types,
        source_application,
        privacy_flags,
        access_behavior,
        ..MacClipboardSnapshot::default()
    };

    if privacy_flags.should_skip() {
        return Ok(snapshot);
    }

    snapshot.file_urls = read_file_urls(pasteboard, &snapshot.types);
    snapshot.png = read_data(pasteboard, &snapshot.types, unsafe { NSPasteboardTypePNG });
    snapshot.html = read_string(pasteboard, &snapshot.types, unsafe { NSPasteboardTypeHTML });
    snapshot.tiff = read_data(pasteboard, &snapshot.types, unsafe { NSPasteboardTypeTIFF });
    snapshot.text = read_string(pasteboard, &snapshot.types, unsafe {
        NSPasteboardTypeString
    });
    Ok(snapshot)
}

#[cfg(target_os = "macos")]
fn has_type(types: &[String], expected: &NSPasteboardType) -> bool {
    let expected = expected.to_string();
    types
        .iter()
        .any(|clipboard_type| clipboard_type == &expected)
}

#[cfg(target_os = "macos")]
fn read_string(
    pasteboard: &NSPasteboard,
    types: &[String],
    clipboard_type: &NSPasteboardType,
) -> Option<String> {
    has_type(types, clipboard_type)
        .then(|| pasteboard.stringForType(clipboard_type))
        .flatten()
        .map(|value| value.to_string())
}

#[cfg(target_os = "macos")]
fn read_data(
    pasteboard: &NSPasteboard,
    types: &[String],
    clipboard_type: &NSPasteboardType,
) -> Option<Vec<u8>> {
    has_type(types, clipboard_type)
        .then(|| pasteboard.dataForType(clipboard_type))
        .flatten()
        .map(|value| value.to_vec())
}

#[cfg(target_os = "macos")]
fn read_file_urls(pasteboard: &NSPasteboard, types: &[String]) -> Option<Vec<String>> {
    if !has_type(types, NSPasteboardTypeFileURL) {
        return None;
    }
    let file_urls = pasteboard
        .pasteboardItems()
        .map(|items| {
            items
                .to_vec()
                .into_iter()
                .filter_map(|item: objc2::rc::Retained<NSPasteboardItem>| {
                    item.stringForType(NSPasteboardTypeFileURL)
                        .map(|value| value.to_string())
                })
                .collect()
        })
        .unwrap_or_default();
    Some(file_urls)
}

#[cfg(test)]
mod tests {
    use std::{cell::Cell, io::Cursor};

    use image::{DynamicImage, ImageOutputFormat, RgbaImage};

    use super::*;

    fn snapshot() -> MacClipboardSnapshot {
        MacClipboardSnapshot {
            change_count: 42,
            text: Some("plain".into()),
            source_application: Some("Example".into()),
            access_behavior: PasteboardAccessBehavior::UnsupportedLegacy,
            ..MacClipboardSnapshot::default()
        }
    }

    fn private_snapshot(marker: &str) -> MacClipboardSnapshot {
        let types = vec![marker.to_string()];
        MacClipboardSnapshot {
            types: types.clone(),
            privacy_flags: MacClipboardPrivacyFlags::from_types(&types),
            text: Some("must not escape".into()),
            ..snapshot()
        }
    }

    fn encoded_image(format: ImageOutputFormat) -> Vec<u8> {
        let image = DynamicImage::ImageRgba8(
            RgbaImage::from_raw(1, 1, vec![1, 2, 3, 255]).expect("valid RGBA image"),
        );
        let mut cursor = Cursor::new(Vec::new());
        image
            .write_to(&mut cursor, format)
            .expect("encode test image");
        cursor.into_inner()
    }

    #[test]
    fn concealed_type_is_skipped() {
        assert_eq!(
            select_clipboard_input(private_snapshot("org.nspasteboard.ConcealedType")).unwrap(),
            None
        );
    }

    #[test]
    fn transient_type_is_skipped() {
        assert_eq!(
            select_clipboard_input(private_snapshot("org.nspasteboard.TransientType")).unwrap(),
            None
        );
    }

    #[test]
    fn auto_generated_type_is_skipped() {
        assert_eq!(
            select_clipboard_input(private_snapshot("org.nspasteboard.AutoGeneratedType")).unwrap(),
            None
        );
    }

    #[test]
    fn legacy_one_password_type_is_skipped() {
        assert_eq!(
            select_clipboard_input(private_snapshot("com.agilebits.onepassword")).unwrap(),
            None
        );
    }

    #[test]
    fn legacy_transient_type_is_skipped() {
        assert_eq!(
            select_clipboard_input(private_snapshot("de.petermaurer.TransientPasteboardType"))
                .unwrap(),
            None
        );
    }

    #[test]
    fn legacy_clipping_type_is_skipped() {
        assert_eq!(
            select_clipboard_input(private_snapshot("com.typeit4me.clipping")).unwrap(),
            None
        );
    }

    #[test]
    fn files_take_priority_over_text_and_keep_item_order() {
        let result = select_clipboard_input(MacClipboardSnapshot {
            file_urls: Some(vec![
                "file:///Users/test/Second%20File.txt".into(),
                "file:///Users/test/First%20File.txt".into(),
            ]),
            ..snapshot()
        })
        .unwrap();
        assert!(matches!(
            result,
            Some(ClipboardInput::Files { files, .. })
                if files == [
                    "/Users/test/Second File.txt",
                    "/Users/test/First File.txt"
                ]
        ));
    }

    #[test]
    fn png_takes_priority_over_html_and_text() {
        let result = select_clipboard_input(MacClipboardSnapshot {
            png: Some(encoded_image(ImageOutputFormat::Png)),
            html: Some("<b>rich</b>".into()),
            ..snapshot()
        })
        .unwrap();
        assert!(matches!(result, Some(ClipboardInput::Image { .. })));
    }

    #[test]
    fn html_takes_priority_over_tiff_and_text() {
        let result = select_clipboard_input(MacClipboardSnapshot {
            html: Some("<b>rich</b>".into()),
            tiff: Some(encoded_image(ImageOutputFormat::Tiff)),
            ..snapshot()
        })
        .unwrap();
        assert!(matches!(result, Some(ClipboardInput::Html { .. })));
    }

    #[test]
    fn tiff_takes_priority_over_text() {
        let result = select_clipboard_input(MacClipboardSnapshot {
            tiff: Some(encoded_image(ImageOutputFormat::Tiff)),
            ..snapshot()
        })
        .unwrap();
        assert!(matches!(result, Some(ClipboardInput::Image { .. })));
    }

    #[test]
    fn text_is_selected_when_it_is_the_only_supported_format() {
        let result = select_clipboard_input(snapshot()).unwrap();
        assert!(matches!(
            result,
            Some(ClipboardInput::Text { text, .. }) if text == "plain"
        ));
    }

    #[test]
    fn localhost_file_url_is_percent_decoded_without_path_normalization() {
        assert_eq!(
            decode_file_url("file://localhost/Users/test/%E6%96%87%E4%BB%B6+name.txt").unwrap(),
            "/Users/test/文件+name.txt"
        );
        assert_eq!(
            decode_file_url("https://example.com/file.txt").unwrap_err(),
            MacClipboardError::InvalidFileUrl
        );
    }

    #[test]
    fn png_decodes_to_canonical_rgba8() {
        assert_eq!(
            decode_image(
                &encoded_image(ImageOutputFormat::Png),
                image::ImageFormat::Png
            )
            .unwrap(),
            CanonicalImage {
                width: 1,
                height: 1,
                rgba8: vec![1, 2, 3, 255],
            }
        );
    }

    #[test]
    fn tiff_decodes_to_canonical_rgba8() {
        assert_eq!(
            decode_image(
                &encoded_image(ImageOutputFormat::Tiff),
                image::ImageFormat::Tiff
            )
            .unwrap(),
            CanonicalImage {
                width: 1,
                height: 1,
                rgba8: vec![1, 2, 3, 255],
            }
        );
    }

    #[test]
    fn invalid_image_returns_safe_error() {
        assert_eq!(
            decode_image(b"not an image", image::ImageFormat::Png).unwrap_err(),
            MacClipboardError::InvalidImage
        );
        assert_eq!(
            validate_canonical_image(2, 1, vec![0; 4]).unwrap_err(),
            MacClipboardError::InvalidImage
        );
    }

    #[test]
    fn change_count_baseline_ignores_same_value_and_processes_change() {
        let mut tracker = ChangeCountTracker::new(7);
        assert!(!tracker.should_process(7));
        assert!(tracker.should_process(8));
        assert!(!tracker.should_process(8));
    }

    #[test]
    fn always_deny_prevents_content_read() {
        let reads = Cell::new(0);
        let result = read_if_allowed(PasteboardAccessBehavior::AlwaysDeny, || {
            reads.set(reads.get() + 1);
            Ok("secret")
        });
        assert_eq!(
            result.unwrap_err(),
            MacClipboardError::PasteboardAccessDenied
        );
        assert_eq!(reads.get(), 0);
    }

    #[test]
    fn always_allow_permits_content_read() {
        assert_eq!(
            read_if_allowed(PasteboardAccessBehavior::AlwaysAllow, || Ok("allowed")).unwrap(),
            "allowed"
        );
    }

    #[test]
    fn unsupported_legacy_system_permits_content_read() {
        assert_eq!(
            read_if_allowed(PasteboardAccessBehavior::UnsupportedLegacy, || Ok("legacy")).unwrap(),
            "legacy"
        );
        assert_eq!(POLL_INTERVAL_MS, 250);
    }
}
